# frozen_string_literal: true

require "bundler/setup"
require "brute"

module Brute
  # One tool invocation requested by the model. Arguments are always a Hash.
  ToolCall = Data.define(:id, :name, :arguments) do
    def initialize(id:, name:, arguments: {})
      super(id: id, name: name.to_s, arguments: arguments.to_h)
    end
  end

  # Brute's canonical, framework-agnostic message. The rest of the stack
  # (middleware, tool loop, persistence) never calls anything beyond
  # #role, #content, #tool_calls, #tool_call_id and #to_h — so any object
  # that duck-types those methods can ride in env[:messages] too. This Data
  # class is simply the canonical implementation.
  #
  #   Brute::Message.new(role: :user, content: "hi")
  #   Brute::Message.new(role: :assistant, content: "", tool_calls: [
  #     Brute::ToolCall.new(id: "tc1", name: "shell", arguments: { "command" => "ls" }),
  #   ])
  #   Brute::Message.new(role: :tool, content: "result", tool_call_id: "tc1")
  # What the model thought before it answered, and the provider's proof that
  # it did.
  #
  # A signature is only meaningful to the provider that issued it: Anthropic
  # verifies its own and rejects a modified block with a 400, and OpenRouter
  # names the format ("anthropic-claude-v1", "openai-responses-v1") because
  # the details only mean anything against the provider that produced them.
  # The log is provider-agnostic and a conversation can be replayed against
  # anyone, so what was signed carries who signed it -- a transport sends the
  # blocks back only when they are its own, and sends the text alone when they
  # are not.
  #
  # The blocks are a sequence, in the order the model produced them, because
  # that is what both providers ask for: "passed back unmodified and in their
  # original order" (Anthropic), "the entire sequence of consecutive reasoning
  # blocks must match the outputs generated by the model" (OpenRouter).
  Reasoning = Data.define(:blocks) do
    def self.build(text: nil, signature: nil, format: nil, blocks: nil)
      blocks = Array(blocks).map { |block| block.is_a?(Reasoning::Block) ? block : Reasoning::Block.new(**block.to_h.transform_keys(&:to_sym)) }

      if blocks.empty? && !(text.to_s.empty? && signature.to_s.empty?)
        blocks = [ Reasoning::Block.new(text: text, signature: signature, format: format) ]
      end

      unless blocks.empty?
        new(blocks: blocks)
      end
    end

    # What the model thought, for anyone reading rather than replaying.
    def text = blocks.filter_map(&:text).join("\n")

    # Whether these blocks may be sent back to this provider as they are. A
    # signature the provider did not issue is worse than no signature: it is
    # a rejected request.
    def signed_by?(format) = blocks.any?(&:signed?) && blocks.all? { |block| block.format.nil? || block.format == format }

    def to_h(...) = { blocks: blocks.map(&:to_h) }
  end

  class Reasoning
    # One block of thinking. :text carries what the model thought; :encrypted
    # and :redacted carry a payload that is not ours to read -- Anthropic's
    # redacted_thinking, or an encrypted reasoning item -- and matter only in
    # that they go back whole.
    Block = Data.define(
      :type,
      :text,
      :signature,
      :format,
      :id,
    ) do
      def initialize(type: :text, text: nil, signature: nil, format: nil, id: nil)
        super(
          type:      type.to_sym,
          text:      text,
          signature: signature,
          format:    format,
          id:        id,
        )
      end

      def signed? = !signature.to_s.empty?

      def to_h(...) = super.compact
    end
  end

  Message = Data.define(
    :role,
    :content,
    :tool_calls,
    :tool_call_id,
    :reasoning,
  ) do
    def initialize(role:, content: nil, tool_calls: nil, tool_call_id: nil, reasoning: nil)
      formatted_calls = tool_calls&.map do |tc|
        tc.is_a?(ToolCall) ? tc : ToolCall.new(**tc.to_h.transform_keys(&:to_sym))
      end

      super(
        role:         role.to_sym,
        content:      content,
        tool_calls:   formatted_calls,
        tool_call_id: tool_call_id,
        reasoning:    coerce(reasoning)
      )
    end

    def tool_call? = !tool_calls.nil? && !tool_calls.empty?
    alias_method :has_tool_calls?, :tool_call?

    # Clean, JSON-ready hash export dropping nil values
    def to_h(...)
      hash = super
      if tool_calls
        hash[:tool_calls] = tool_calls.map(&:to_h)
      end
      if reasoning
        hash[:reasoning] = reasoning.to_h
      end
      hash.compact
    end

    private

      # Reasoning read back off disk is a hash, and a provider that reports
      # nothing but the text is still reporting reasoning.
      def coerce(reasoning)
        case reasoning
        in nil | Reasoning then reasoning
        in String => text then Reasoning.build(text: text)
        else Reasoning.build(**reasoning.to_h.transform_keys(&:to_sym))
        end
      end
  end

  # The in-memory conversation log is just a plain Array of Brute::Message.
  # This module adds a little sugar for appending role-tagged messages; mix it
  # into an array via `Brute.log`. Persistence is NOT here — loading/saving the
  # log to disk is the Brute::Middleware::SessionLog middleware's job.
  module Messages
    def user(content);      self << Message.new(role: :user,      content: content); end
    def assistant(content); self << Message.new(role: :assistant, content: content); end
    def system(content);    self << Message.new(role: :system,    content: content); end

    def tool(content, tool_call_id:)
      self << Message.new(role: :tool, content: content, tool_call_id: tool_call_id)
    end
  end

  # Build a fresh conversation log (an Array + Messages sugar), optionally
  # seeded with messages.
  #
  #   log = Brute.log
  #   log.user("hello")
  #   Brute.log(Brute::Message.new(role: :user, content: "hi"))
  def self.log(*messages)
    [].extend(Messages).tap { |log| messages.flatten.each { |m| log << m } }
  end
end

__END__

describe "brute/messages" do
  it "appends role-tagged messages" do
    log = Brute.log
    log.user("hi")
    log.assistant("hello")
    log.map(&:role).should == [:user, :assistant]
    log.first.content.should == "hi"
  end

  it "appends tool results" do
    log = Brute.log
    log.tool("result", tool_call_id: "tc1")
    log.last.role.should == :tool
    log.last.tool_call_id.should == "tc1"
  end

  it "seeds from given messages" do
    m = Brute::Message.new(role: :user, content: "seed")
    Brute.log(m).should == [m]
  end

  it "is a plain Array (no special class)" do
    Brute.log.should.be.kind_of?(Array)
  end

  it "symbolizes string roles" do
    Brute::Message.new(role: "user", content: "hi").role.should == :user
  end

  it "coerces tool_calls hashes into ToolCall" do
    m = Brute::Message.new(
      role: :assistant, content: "",
      tool_calls: [{ "id" => "tc1", "name" => "shell", "arguments" => { "command" => "ls" } }]
    )
    m.tool_calls.first.name.should == "shell"
    m.tool_calls.first.arguments.should == { "command" => "ls" }
    m.tool_call?.should.be.true
  end

  it "round-trips through to_h" do
    m = Brute::Message.new(role: :assistant, content: "",
                           tool_calls: [{ id: "tc1", name: "shell", arguments: {} }])
    Brute::Message.new(**m.to_h).should == m
  end

  it "to_h drops nil fields" do
    Brute::Message.new(role: :user, content: "hi").to_h.should == { role: :user, content: "hi" }
  end
end
